In [105]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [106]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import RandomizedSearchCV, train_test_split
from sklearn.preprocessing import StandardScaler

In [107]:
from sklearn.datasets import load_breast_cancer

In [108]:
lbc = load_breast_cancer()
bc = pd.DataFrame(lbc.data, columns = lbc.feature_names)
bc['target'] = lbc.target

train_bc, test_bc = train_test_split(bc, test_size=0.2, random_state=123)

In [109]:
rf = RandomForestClassifier(oob_score=True)

In [110]:
n_estimators = np.arange(5, 20)
criterion = ['gini', 'entropy']
min_samples_split = [30, 40, 50, 60]
min_samples_leaf = [20, 25, 30, 35]
max_features = ['sqrt', 'log2', 0.2, 0.45, 0.7]

In [111]:
param_rf = {'n_estimators': n_estimators,
           'criterion': criterion,
           'min_samples_split': min_samples_split,
           'min_samples_leaf': min_samples_leaf,
           'max_features': max_features}

In [112]:
rf_random = RandomizedSearchCV(estimator = rf, param_distributions=param_rf, n_iter=25, n_jobs=-1)

In [113]:
rf_random.fit(train_bc.drop(columns='target'), train_bc.target)

RandomizedSearchCV(estimator=RandomForestClassifier(oob_score=True), n_iter=25,
                   n_jobs=-1,
                   param_distributions={'criterion': ['gini', 'entropy'],
                                        'max_features': ['sqrt', 'log2', 0.2,
                                                         0.45, 0.7],
                                        'min_samples_leaf': [20, 25, 30, 35],
                                        'min_samples_split': [30, 40, 50, 60],
                                        'n_estimators': array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])})

In [114]:
rf_random.best_estimator_

RandomForestClassifier(max_features=0.45, min_samples_leaf=20,
                       min_samples_split=40, n_estimators=19, oob_score=True)

In [115]:
rf_random.predict(test_bc.drop(columns='target'))

array([1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0,
       1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1,
       0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0,
       1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1,
       0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 0])

In [116]:
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.compose import ColumnTransformer

In [117]:
housing = pd.read_excel('housing.xlsx')

In [118]:
housing.head()

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0    -122.23     37.88                  41          880           129.0   
1    -122.22     37.86                  21         7099          1106.0   
2    -122.24     37.85                  52         1467           190.0   
3    -122.25     37.85                  52         1274           235.0   
4    -122.25     37.85                  52         1627           280.0   

   population  households  median_income ocean_proximity  median_house_value  
0         322         126         8.3252        NEAR BAY              452600  
1        2401        1138         8.3014        NEAR BAY              358500  
2         496         177         7.2574        NEAR BAY              352100  
3         558         219         5.6431        NEAR BAY              341300  
4         565         259         3.8462        NEAR BAY              342200

In [119]:
#Check for missing values
housing.isna().sum()

longitude               0
latitude                0
housing_median_age      0
total_rooms             0
total_bedrooms        207
population              0
households              0
median_income           0
ocean_proximity         0
median_house_value      0
dtype: int64

In [120]:
num_cols = housing.select_dtypes(exclude='O').columns
cat_cols = housing.select_dtypes(include='O').columns

In [159]:
cat_cols

Index(['ocean_proximity'], dtype='object')

In [157]:
np.shape(num_cols)

(9,)

In [121]:
si = SimpleImputer(strategy='median')

In [122]:
si.fit_transform(housing[num_cols])

array([[-1.2223e+02,  3.7880e+01,  4.1000e+01, ...,  1.2600e+02,
         8.3252e+00,  4.5260e+05],
       [-1.2222e+02,  3.7860e+01,  2.1000e+01, ...,  1.1380e+03,
         8.3014e+00,  3.5850e+05],
       [-1.2224e+02,  3.7850e+01,  5.2000e+01, ...,  1.7700e+02,
         7.2574e+00,  3.5210e+05],
       ...,
       [-1.2122e+02,  3.9430e+01,  1.7000e+01, ...,  4.3300e+02,
         1.7000e+00,  9.2300e+04],
       [-1.2132e+02,  3.9430e+01,  1.8000e+01, ...,  3.4900e+02,
         1.8672e+00,  8.4700e+04],
       [-1.2124e+02,  3.9370e+01,  1.6000e+01, ...,  5.3000e+02,
         2.3886e+00,  8.9400e+04]])

In [123]:
ss=StandardScaler()

In [124]:
ss.fit_transform(si.fit_transform(housing[num_cols]))

array([[-1.32783522,  1.05254828,  0.98214266, ..., -0.97703285,
         2.34476576,  2.12963148],
       [-1.32284391,  1.04318455, -0.60701891, ...,  1.66996103,
         2.33223796,  1.31415614],
       [-1.33282653,  1.03850269,  1.85618152, ..., -0.84363692,
         1.7826994 ,  1.25869341],
       ...,
       [-0.8237132 ,  1.77823747, -0.92485123, ..., -0.17404163,
        -1.14259331, -0.99274649],
       [-0.87362627,  1.77823747, -0.84539315, ..., -0.39375258,
        -1.05458292, -1.05860847],
       [-0.83369581,  1.75014627, -1.00430931, ...,  0.07967221,
        -0.78012947, -1.01787803]])

In [142]:
num_pipeline = Pipeline([('imputer', SimpleImputer(strategy='median')), ('std_scaler', StandardScaler())])

In [143]:
num_pipeline.fit_transform(housing[num_cols])

array([[-1.32783522,  1.05254828,  0.98214266, ..., -0.97703285,
         2.34476576,  2.12963148],
       [-1.32284391,  1.04318455, -0.60701891, ...,  1.66996103,
         2.33223796,  1.31415614],
       [-1.33282653,  1.03850269,  1.85618152, ..., -0.84363692,
         1.7826994 ,  1.25869341],
       ...,
       [-0.8237132 ,  1.77823747, -0.92485123, ..., -0.17404163,
        -1.14259331, -0.99274649],
       [-0.87362627,  1.77823747, -0.84539315, ..., -0.39375258,
        -1.05458292, -1.05860847],
       [-0.83369581,  1.75014627, -1.00430931, ...,  0.07967221,
        -0.78012947, -1.01787803]])

In [144]:
from sklearn.preprocessing import OneHotEncoder

In [177]:
housing[num_cols].head()

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0    -122.23     37.88                  41          880           129.0   
1    -122.22     37.86                  21         7099          1106.0   
2    -122.24     37.85                  52         1467           190.0   
3    -122.25     37.85                  52         1274           235.0   
4    -122.25     37.85                  52         1627           280.0   

   population  households  median_income  median_house_value  
0         322         126         8.3252              452600  
1        2401        1138         8.3014              358500  
2         496         177         7.2574              352100  
3         558         219         5.6431              341300  
4         565         259         3.8462              342200

In [160]:
preprocessing = ColumnTransformer([('num', num_pipeline, num_cols), ('cat', OneHotEncoder(handle_unknown='ignore'), cat_cols)])

In [171]:
np.shape(preprocessing.fit_transform(housing))

(20640, 14)

In [146]:
pd.DataFrame(preprocessing.fit_transform(housing))

0         1         2         3         4         5         6   \
0     -1.327835  1.052548  0.982143 -0.804819 -0.972476 -0.974429 -0.977033   
1     -1.322844  1.043185 -0.607019  2.045890  1.357143  0.861439  1.669961   
2     -1.332827  1.038503  1.856182 -0.535746 -0.827024 -0.820777 -0.843637   
3     -1.337818  1.038503  1.856182 -0.624215 -0.719723 -0.766028 -0.733781   
4     -1.337818  1.038503  1.856182 -0.462404 -0.612423 -0.759847 -0.629157   
...         ...       ...       ...       ...       ...       ...       ...   
20635 -0.758826  1.801647 -0.289187 -0.444985 -0.388283 -0.512592 -0.443449   
20636 -0.818722  1.806329 -0.845393 -0.888704 -0.922403 -0.944405 -1.008420   
20637 -0.823713  1.778237 -0.924851 -0.174995 -0.123608 -0.369537 -0.174042   
20638 -0.873626  1.778237 -0.845393 -0.355600 -0.304827 -0.604429 -0.393753   
20639 -0.833696  1.750146 -1.004309  0.068408  0.188757 -0.033977  0.079672   

             7         8    9    10   11   12   13  
0      2.344766  2.129631  0.0  0.0  0.0  1.0  0.0  
1      2.332238  1.314156  0.0  0.0  0.0  1.0  0.0  
2      1.782699  1.258693  0.0  0.0  0.0  1.0  0.0  
3      0.932968  1.165100  0.0  0.0  0.0  1.0  0.0  
4     -0.012881  1.172900  0.0  0.0  0.0  1.0  0.0  
...         ...       ...  ...  ...  ...  ...  ...  
20635 -1.216128 -1.115804  0.0  1.0  0.0  0.0  0.0  
20636 -0.691593 -1.124470  0.0  1.0  0.0  0.0  0.0  
20637 -1.142593 -0.992746  0.0  1.0  0.0  0.0  0.0  
20638 -1.054583 -1.058608  0.0  1.0  0.0  0.0  0.0  
20639 -0.780129 -1.017878  0.0  1.0  0.0  0.0  0.0  

[20640 rows x 14 columns]

In [147]:
oe = OneHotEncoder()

In [148]:
oe.fit_transform(housing[['ocean_proximity']],)

<20640x5 sparse matrix of type '<class 'numpy.float64'>'
	with 20640 stored elements in Compressed Sparse Row format>

In [149]:
oe.feature_names_in_

array(['ocean_proximity'], dtype=object)

In [150]:
oe.categories_

[array(['<1H OCEAN', 'INLAND', 'ISLAND', 'NEAR BAY', 'NEAR OCEAN'],
       dtype=object)]

In [151]:
from xgboost import XGBRegressor

In [168]:
xgb = XGBRegressor()

In [165]:
final_pipeline = Pipeline([('preprocess', preprocessing), ('xgb', xgb)])

In [169]:
final_pipeline

Pipeline(steps=[('preprocess',
                 ColumnTransformer(transformers=[('num',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer(strategy='median')),
                                                                  ('std_scaler',
                                                                   StandardScaler())]),
                                                  Index(['longitude', 'latitude', 'housing_median_age', 'total_rooms',
       'total_bedrooms', 'population', 'households', 'median_income',
       'median_house_value'],
      dtype='object')),
                                                 ('cat',
                                                  OneHotEncoder(ha...
                              feature_types=None, gamma=None, grow_policy=None,
                              importance_type=None,
                              interaction_constraints=None, learning_rate=None,
                              max_bin=None, max_cat_threshold=None,
                              max_cat_to_onehot=None, max_delta_step=None,
                              max_depth=None, max_leaves=None,
                              min_child_weight=None, missing=nan,
                              monotone_constraints=None, multi_strategy=None,
                              n_estimators=None, n_jobs=None,
                              num_parallel_tree=None, random_state=None, ...))])

In [130]:
#xgb__
# gbm_param = {
#     'xgb__n_estimators':[40, 50, 60],
#     'xgb__max_depth':[4,5 ,7],
#     'xgb__learning_rate': [0.4, 0.2, 0.5, 0.8],
#     'xgb__colsample_bytree':[0.01, 0.02, 0.03, 0.04, 0.05, 0.08]
    
# }
gbm_param = {
    'xgb__n_estimators': [40,50,60],
    'xgb__max_depth':[4,6,8],
    'xgb__learning_rate':[.4,.2,.5,.8],
    'xgb__colsample_bytree':[.01,.02,.03,.4,.5,.8]
}

In [131]:
from sklearn.model_selection import RandomizedSearchCV

In [183]:
housing.drop(columns='median_house_value')

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0        -122.23     37.88                  41          880           129.0   
1        -122.22     37.86                  21         7099          1106.0   
2        -122.24     37.85                  52         1467           190.0   
3        -122.25     37.85                  52         1274           235.0   
4        -122.25     37.85                  52         1627           280.0   
...          ...       ...                 ...          ...             ...   
20635    -121.09     39.48                  25         1665           374.0   
20636    -121.21     39.49                  18          697           150.0   
20637    -121.22     39.43                  17         2254           485.0   
20638    -121.32     39.43                  18         1860           409.0   
20639    -121.24     39.37                  16         2785           616.0   

       population  households  median_income ocean_proximity  
0             322         126         8.3252        NEAR BAY  
1            2401        1138         8.3014        NEAR BAY  
2             496         177         7.2574        NEAR BAY  
3             558         219         5.6431        NEAR BAY  
4             565         259         3.8462        NEAR BAY  
...           ...         ...            ...             ...  
20635         845         330         1.5603          INLAND  
20636         356         114         2.5568          INLAND  
20637        1007         433         1.7000          INLAND  
20638         741         349         1.8672          INLAND  
20639        1387         530         2.3886          INLAND  

[20640 rows x 9 columns]

In [184]:
housing.median_house_value

0        452600
1        358500
2        352100
3        341300
4        342200
          ...  
20635     78100
20636     77100
20637     92300
20638     84700
20639     89400
Name: median_house_value, Length: 20640, dtype: int64

In [186]:
final_pipeline

Pipeline(steps=[('preprocess',
                 ColumnTransformer(transformers=[('num',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer(strategy='median')),
                                                                  ('std_scaler',
                                                                   StandardScaler())]),
                                                  Index(['longitude', 'latitude', 'housing_median_age', 'total_rooms',
       'total_bedrooms', 'population', 'households', 'median_income',
       'median_house_value'],
      dtype='object')),
                                                 ('cat',
                                                  OneHotEncoder(ha...
                              feature_types=None, gamma=None, grow_policy=None,
                              importance_type=None,
                              interaction_constraints=None, learning_rate=None,
                              max_bin=None, max_cat_threshold=None,
                              max_cat_to_onehot=None, max_delta_step=None,
                              max_depth=None, max_leaves=None,
                              min_child_weight=None, missing=nan,
                              monotone_constraints=None, multi_strategy=None,
                              n_estimators=None, n_jobs=None,
                              num_parallel_tree=None, random_state=None, ...))])

In [187]:
final_pipeline.fit(housing, housing.median_house_value)

Pipeline(steps=[('preprocess',
                 ColumnTransformer(transformers=[('num',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer(strategy='median')),
                                                                  ('std_scaler',
                                                                   StandardScaler())]),
                                                  Index(['longitude', 'latitude', 'housing_median_age', 'total_rooms',
       'total_bedrooms', 'population', 'households', 'median_income',
       'median_house_value'],
      dtype='object')),
                                                 ('cat',
                                                  OneHotEncoder(ha...
                              feature_types=None, gamma=None, grow_policy=None,
                              importance_type=None,
                              interaction_constraints=None, learning_rate=None,
                              max_bin=None, max_cat_threshold=None,
                              max_cat_to_onehot=None, max_delta_step=None,
                              max_depth=None, max_leaves=None,
                              min_child_weight=None, missing=nan,
                              monotone_constraints=None, multi_strategy=None,
                              n_estimators=None, n_jobs=None,
                              num_parallel_tree=None, random_state=None, ...))])

In [170]:
xgb_rscv = RandomizedSearchCV(estimator=final_pipeline, scoring='neg_mean_squared_error', param_distributions=gbm_param, n_iter=20, n_jobs=-1)

In [188]:
xgb_rscv.fit(housing, housing.median_house_value)

RandomizedSearchCV(estimator=Pipeline(steps=[('preprocess',
                                              ColumnTransformer(transformers=[('num',
                                                                               Pipeline(steps=[('imputer',
                                                                                                SimpleImputer(strategy='median')),
                                                                                               ('std_scaler',
                                                                                                StandardScaler())]),
                                                                               Index(['longitude', 'latitude', 'housing_median_age', 'total_rooms',
       'total_bedrooms', 'population', 'households', 'median_income',
       'median_house_value'],
      dtype='obje...
                                                           missing=nan,
                                                           monotone_constraints=None,
                                                           multi_strategy=None,
                                                           n_estimators=None,
                                                           n_jobs=None,
                                                           num_parallel_tree=None,
                                                           random_state=None, ...))]),
                   n_iter=20, n_jobs=-1,
                   param_distributions={'xgb__colsample_bytree': [0.01, 0.02,
                                                                  0.03, 0.4,
                                                                  0.5, 0.8],
                                        'xgb__learning_rate': [0.4, 0.2, 0.5,
                                                               0.8],
                                        'xgb__max_depth': [4, 6, 8],
                                        'xgb__n_estimators': [40, 50, 60]},
                   scoring='neg_mean_squared_error')

In [ ]:
xgb_rscv