### Collaborative filtering

In [7]:
import pandas as pd
import numpy as np

In [10]:
data = pd.DataFrame(columns = ['user_'+str(i) for i in range(10)], index = ['movie_'+str(i) for i in range(10)])

In [16]:
for i in range(10):
    for j in range(10):
        data['user_'+str(i) ]['movie_'+str(j) ] = np.random.randint(low=0, high=6, dtype=int)

In [17]:
data

user_0 user_1 user_2 user_3 user_4 user_5 user_6 user_7 user_8 user_9
movie_0      4      1      4      2      1      0      5      3      1      5
movie_1      0      2      5      3      1      0      2      2      5      1
movie_2      0      2      2      0      3      1      1      0      3      5
movie_3      4      5      1      5      0      0      2      5      0      0
movie_4      1      0      1      5      1      5      3      1      1      3
movie_5      2      4      0      3      2      5      4      4      0      5
movie_6      3      4      0      3      1      4      3      5      0      1
movie_7      3      0      4      2      1      5      2      1      0      0
movie_8      4      5      1      4      4      2      0      2      2      0
movie_9      3      5      0      5      5      0      5      2      3      1

In [23]:
for i in range(10):
    data['user_'+str(i)] -= data['user_'+str(i)].mean()

In [24]:
data

user_0 user_1 user_2 user_3 user_4 user_5 user_6 user_7 user_8 user_9
movie_0    1.6   -1.8    2.2   -1.2   -0.9   -2.2    2.3    0.5   -0.5    2.9
movie_1   -2.4   -0.8    3.2   -0.2   -0.9   -2.2   -0.7   -0.5    3.5   -1.1
movie_2   -2.4   -0.8    0.2   -3.2    1.1   -1.2   -1.7   -2.5    1.5    2.9
movie_3    1.6    2.2   -0.8    1.8   -1.9   -2.2   -0.7    2.5   -1.5   -2.1
movie_4   -1.4   -2.8   -0.8    1.8   -0.9    2.8    0.3   -1.5   -0.5    0.9
movie_5   -0.4    1.2   -1.8   -0.2    0.1    2.8    1.3    1.5   -1.5    2.9
movie_6    0.6    1.2   -1.8   -0.2   -0.9    1.8    0.3    2.5   -1.5   -1.1
movie_7    0.6   -2.8    2.2   -1.2   -0.9    2.8   -0.7   -1.5   -1.5   -2.1
movie_8    1.6    2.2   -0.8    0.8    2.1   -0.2   -2.7   -0.5    0.5   -2.1
movie_9    0.6    2.2   -1.8    1.8    3.1   -2.2    2.3   -0.5    1.5   -1.1

In [25]:
from sklearn.metrics.pairwise import cosine_distances, cosine_similarity

In [26]:
movie_0 = data[data.index =='movie_0']

In [27]:
movie_0

user_0 user_1 user_2 user_3 user_4 user_5 user_6 user_7 user_8 user_9
movie_0    1.6   -1.8    2.2   -1.2   -0.9   -2.2    2.3    0.5   -0.5    2.9

In [29]:
other_movies = data[data.index != 'movie_0']

In [30]:
cosine_similarity(movie_0, other_movies)

array([[ 0.10921556,  0.17059368, -0.137435  , -0.12804031,  0.00440072,
        -0.34858288, -0.02389182, -0.64593989, -0.17825257]])

In [31]:
from sklearn.neighbors import NearestNeighbors

In [32]:
knn = NearestNeighbors(metric='cosine')

In [33]:
knn.fit(data.values)

NearestNeighbors(metric='cosine')

In [34]:
distance, indices = knn.kneighbors(data.values, n_neighbors=4)

In [35]:
indices

array([[0, 2, 1, 5],
       [1, 2, 0, 7],
       [2, 1, 0, 4],
       [3, 6, 8, 9],
       [4, 7, 5, 2],
       [5, 6, 4, 0],
       [6, 5, 3, 8],
       [7, 4, 1, 6],
       [8, 9, 3, 6],
       [9, 8, 3, 1]], dtype=int64)

In [37]:
distance

array([[1.11022302e-16, 8.29406323e-01, 8.90784435e-01, 9.95599277e-01],
       [0.00000000e+00, 6.34201079e-01, 8.90784435e-01, 9.70120704e-01],
       [0.00000000e+00, 6.34201079e-01, 8.29406323e-01, 9.86448304e-01],
       [0.00000000e+00, 4.79694531e-01, 6.46859668e-01, 8.05659312e-01],
       [1.11022302e-16, 5.63442528e-01, 7.16041242e-01, 9.86448304e-01],
       [2.22044605e-16, 4.44724863e-01, 7.16041242e-01, 9.95599277e-01],
       [0.00000000e+00, 4.44724863e-01, 4.79694531e-01, 9.02728256e-01],
       [1.11022302e-16, 5.63442528e-01, 9.70120704e-01, 1.01088044e+00],
       [0.00000000e+00, 5.73251765e-01, 6.46859668e-01, 9.02728256e-01],
       [1.11022302e-16, 5.73251765e-01, 8.05659312e-01, 1.06057533e+00]])